from ddgs import DDGS
from groq import Groq
from fpdf import FPDF
import requests
from bs4 import BeautifulSoup
import os, tempfile, smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))
GMAIL_ADDRESS = os.getenv("GMAIL_ADDRESS")
GMAIL_APP_PASSWORD = os.getenv("GMAIL_APP_PASSWORD")

def search_web(topic: str, max_results: int = 5) -> list:
    results = []
    with DDGS() as ddgs:
        for r in ddgs.text(topic, max_results=max_results):
            results.append({"title": r["title"], "url": r["href"], "snippet": r["body"]})
    return results

def scrape_url(url: str) -> str:
    try:
        res = requests.get(url, timeout=8, headers={"User-Agent": "Mozilla/5.0"})
        soup = BeautifulSoup(res.text, "html.parser")
        # Remove scripts and styles
        for tag in soup(["script", "style", "nav", "footer"]):
            tag.decompose()
        return soup.get_text(separator=" ", strip=True)[:3000]
    except Exception:
        return ""

def generate_report(topic: str, sources: list) -> str:
    combined = "\n\n".join(
        f"Source: {s['title']} ({s['url']})\n{s['content']}"
        for s in sources if s["content"]
    )
    prompt = f"""You are a research assistant. Based on the following web sources, write a comprehensive research report on: "{topic}"

Structure the report with:
1. Executive Summary
2. Key Findings (with subsections)
3. Analysis
4. Conclusion
5. Sources

Sources:
{combined}

Write in a professional, detailed manner. Be thorough and insightful."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",  # Use larger model for research
        messages=[{"role": "user", "content": prompt}],
        max_tokens=4000
    )
    return response.choices[0].message.content

def clean_text(text: str) -> str:
    """Remove non-latin characters that break fpdf."""
    return text.encode("latin-1", "replace").decode("latin-1")

def create_pdf(topic: str, report_text: str) -> str:
    pdf = FPDF()
    pdf.set_margins(20, 20, 20)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(50, 50, 150)
    pdf.cell(0, 10, clean_text(f"Research Report: {topic}"), ln=True, align="C")
    pdf.ln(2)

    # Divider line
    pdf.set_draw_color(150, 150, 200)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(6)

    # Body text
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(40, 40, 40)

    for line in report_text.split("\n"):
        line = clean_text(line.strip())
        if not line:
            pdf.ln(3)
            continue

        # Bold heading detection
        if line.startswith("**") and line.endswith("**"):
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(50, 50, 150)
            pdf.multi_cell(170, 7, line.replace("**", "").strip())
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(40, 40, 40)
        elif len(line) > 1 and line[0].isdigit() and line[1] in ".):":
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(50, 50, 150)
            pdf.multi_cell(170, 7, line)
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(40, 40, 40)
        else:
            pdf.multi_cell(170, 6, line)

    tmp_path = os.path.join(
        tempfile.gettempdir(),
        f"research_{topic[:20].replace(' ', '_')}.pdf"
    )
    pdf.output(tmp_path)
    return tmp_path

def send_email_with_pdf(topic: str, pdf_path: str, to_email: str):
    msg = MIMEMultipart()
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = to_email
    msg["Subject"] = f"📄 Research Report: {topic}"

    body = f"""Hi,

Your research report on "{topic}" is ready! Please find it attached.

This report was generated by your RAG Personal Assistant using live web sources.

Best regards,
Your RAG Assistant 🤖"""

    msg.attach(MIMEText(body, "plain"))

    # Attach PDF
    with open(pdf_path, "rb") as f:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(f.read())
    encoders.encode_base64(part)
    part.add_header("Content-Disposition", f"attachment; filename=Research_{topic[:30]}.pdf")
    msg.attach(part)

    # Send via Gmail SMTP
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.sendmail(GMAIL_ADDRESS, to_email, msg.as_string())

def run_research(topic: str, to_email: str):
    """Full research pipeline — call this in a background thread."""
    try:
        print(f"🔬 Researching: {topic}")

        # 1. Search web
        search_results = search_web(topic, max_results=5)

        # 2. Scrape each result
        sources = []
        for r in search_results:
            content = scrape_url(r["url"])
            sources.append({**r, "content": content})

        # 3. Generate report
        report = generate_report(topic, sources)

        # 4. Create PDF
        pdf_path = create_pdf(topic, report)

        # 5. Send email
        send_email_with_pdf(topic, pdf_path, to_email)

        print(f"✅ Research on '{topic}' emailed to {to_email}")
    except Exception as e:
        print(f"❌ Research failed: {e}")